# Generated by Django 5.0.6 on 2024-08-04 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BlogName", models.CharField(default="", max_length=100)),
                ("BlogDescription", models.CharField(default="", max_length=500)),
                ("BlogKeywords", models.CharField(default="", max_length=5000)),
                ("BlogDateAdded", models.CharField(default="", max_length=20)),
                ("BlogImage", models.CharField(default="", max_length=5000)),
                ("BlogSlug", models.CharField(default="", max_length=400)),
                (
                    "BlogCategory",
                    models.CharField(
                        choices=[
                            ("Top Trends", "Top Trends"),
                            ("Innovations", "Innovations"),
                            ("Entertainment", "Entertainment"),
                            ("AI", "AI"),
                            ("Innovations", "Innovations"),
                            ("Good Reads", "Good Reads"),
                            ("Digital Marketing", "Digital Marketing"),
                            ("Programming", "Programming"),
                        ],
                        default="",
                        max_length=100,
                    ),
                ),
                ("BlogPost", models.TextField(default="", max_length=10000)),
                ("BlogAuthor", models.CharField(default="", max_length=50)),
                ("Views", models.CharField(default="0", max_length=50)),
                (
                    "Likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="UserLikes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
