# Generated by Django 5.0.6 on 2024-08-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrcaBlogsWebsite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="BlogID",
            field=models.CharField(default="", max_length=10),
        ),
    ]
