# Generated by Django 5.0.6 on 2024-08-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrcaBlogsWebsite", "0003_postcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcomment",
            name="PostID",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
