# Generated by Django 5.0.6 on 2024-08-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrcaBlogsWebsite", "0004_postcomment_postid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="BlogCategory",
            field=models.CharField(
                choices=[
                    ("Top Trends", "Top Trends"),
                    ("Innovations", "Innovations"),
                    ("Entertainment", "Entertainment"),
                    ("AI", "AI"),
                    ("Innovations", "Innovations"),
                    ("Good Reads", "Good Reads"),
                    ("Digital Marketing", "Digital Marketing"),
                    ("Programming", "Programming"),
                    ("Technology", "Technology"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
